Update installation instructions
NCAR/geocat-datafiles pull request #31
Opened 2022-04-19 15:47 UTC by hCraker

Clarification on how to update and install geocat packages in a pre-existing environment was requested in this issue https://github.com/NCAR/GeoCAT/issues/43. After speaking with the user who suggested these changes, it was determined that she was looking at the geocat-comp documentation. These instructions are being added to the contributor's guide https://github.com/NCAR/GeoCAT/pull/47, but also should be added to each GeoCAT repository.

This PR updates INSTALLATION.md to include instructions for how to ensure the environment and `geocat-datafiles` is up to date.

I added instruction for installing and managing the package through both Conda and PyPi

2022-04-19 21:23 UTC, erogluorhan reviewed
Please add a "Building GeoCAT-datafiles from source" section for consistency, and see my inline comments in addition.

2022-04-19 21:23 UTC, erogluorhan commented on INSTALLATION.md
> +## Installing GeoCAT-comp in a Pre-existing Conda Environment
"GeoCAT-datafiles"

2022-04-19 21:23 UTC, erogluorhan commented on INSTALLATION.md
> +## Updating GeoCAT-comp via Conda
"GeoCAT-datafiles"

2022-04-19 21:23 UTC, erogluorhan commented on INSTALLATION.md
> +Installing GeoCAT-datafiles via PyPi
GeoCAT-datafiles is not on PyPI for now

2022-04-20 16:42 UTC, hCraker commented on INSTALLATION.md
> +Installing GeoCAT-datafiles via PyPi
I'm not sure how to add it to PyPi, but we may want to for consistency with the other repos. I can open an issue to add it to PyPi and remove this section from the instructions until that issue is closed.

2022-04-20 17:00 UTC, erogluorhan commented on INSTALLATION.md
> +Installing GeoCAT-datafiles via PyPi
See this [GitHub action for publishing geocat-comp to PyPI](https://github.com/NCAR/geocat-comp/pull/115) for reference. It could be a nice practice for you to get further understanding of Github actions and PyPI environment together. I'd recommend to get PyPi work done first and then this docs PR merged including the PyPI section for full consistency.

2022-04-20 17:03 UTC, erogluorhan requested changes
Please add a "Building GeoCAT-datafiles from source" section for consistency with other GeoCAT repos

2022-04-21 16:24 UTC, erogluorhan requested changes
We are getting there! Please address inline comments.

2022-04-21 16:24 UTC, erogluorhan commented on build_envs/environment.yml
> +      - pre-commit
We figured out no need to use pip for pre-commit. You can remove `pip` dependency above and this pre-commit dependency through pip, and instead add only `pre_commit` dependency.

2022-04-21 16:24 UTC, erogluorhan commented on setup.py
> +
Please also add the blocks that are related to "long_description" as in geocat-comp's setup.py. It will help PyPI show the repo README file on the package page.

2022-04-21 16:24 UTC, erogluorhan commented on setup.py
> +    description="""This repository contains the many data files that are used by GeoCAT-examples and possibly other GeoCAT components to test or demonstrate GeoCAT functionality. """
Not only the above additions but also all of the additions into `setup()` as in geocat-comp's PR are required for PyPI, e.g. `maintainer`, `classifiers`, etc.

2022-04-26 16:55 UTC, erogluorhan commented on build_envs/environment.yml
> +  - pip
You can remove pip dependency now

2022-04-26 16:56 UTC, erogluorhan commented on build_envs/environment.yml
> +  - pre-commit
Please double check if it should be `pre_commit` or `pre-commit`, and add a new line at the end of this file.

2022-04-26 17:00 UTC, pilotchute commented
@hCraker I strongly recommend that you simply copy and use the metal.yaml file from our [feedstock](https://github.com/NCAR/geocat-datafiles-feedstock) repo.

2022-04-26 18:23 UTC, erogluorhan approved these changes

2022-04-27 16:58 UTC, hCraker commented
> It shouldn't affect `build_envs/environment.yml`, so you should be good to copy that meta.yaml.

Sounds good. I'll copy over that file before merging.

2022-04-27 17:18 UTC, erogluorhan commented
> @erogluorhan @pilotchute I updated the meta.yaml file to match the one in the feedstock repo. Please let me know if it looks good to go!

Yes, it looks good to me!

2022-04-28 19:30 UTC, merged