add ncl dewtemp_trh outputs
NCAR/geocat-datafiles pull request #76
Opened 2024-08-28 19:08 UTC by cyschneck

Adds `dewtemp_trh` output values to use for `dewtemp` in applications (https://github.com/NCAR/geocat-applications/issues/100)

2024-08-28 20:36 UTC, kafitzgerald reviewed
It looks like it's fairly easy to programmatically generate and check inputs / outputs for this function.  Can this be thinned down a bit and live in GeoCAT applications?  I feel like that's what we did for some of the other functions.

Totally possible I missed something here too (apparently I did).

2024-08-28 21:50 UTC, anissa111 commented
Outside of the conversation on location that I'll leave to our slack conversation, I have a small suggestion. Assuming it would be minimal effort, I think it might be useful to include the corresponding inputs in the file as additional columns. As in, outputting columns of temp, rh, and then the calculated dewtemp. This would make it easier to recreate and compare over in geocat-applications, as well.

Also, the ncl script itself should live over in geocat-applications.

2024-08-29 21:33 UTC, cyschneck commented
> Outside of the conversation on location that I'll leave to our slack conversation, I have a small suggestion. Assuming it would be minimal effort, I think it might be useful to include the corresponding inputs in the file as additional columns. As in, outputting columns of temp, rh, and then the calculated dewtemp. This would make it easier to recreate and compare over in geocat-applications, as well.
> 
> Also, the ncl script itself should live over in geocat-applications.

Removed `dewtemp_trh.ncl` and included the tk/rh as values in a comma separated columns with dewtemp

2024-08-30 00:40 UTC, kafitzgerald requested changes
registry file needs an update, but otherwise looks good.

2024-08-30 00:40 UTC, kafitzgerald commented on registry.txt
> +applications_files/ncl_outputs/dewtemp_trh_output.txt db95d50e76287382984bf40e1dcf2f79e9b8bbe72adcef0d110c59beceac8b11
I think these still need an update, but otherwise looks good to me.

2024-08-30 15:54 UTC, anissa111 approved these changes

2024-08-30 16:21 UTC, kafitzgerald approved these changes

2024-08-30 16:22 UTC, merged